CREATE TABLE gas_t (pdvid STRING, cp STRING, pop STRING, lat STRING, lon STRING, dat STRING, gasid STRING, gasname STRING, price INT)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '59'
STORED AS TEXTFILE;

LOAD DATA INPATH '/tmp/maria_dev' INTO TABLE gas_t;

CREATE TABLE gas
STORED AS PARQUETFILE
AS SELECT * from gas_t;
